// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_2buZUiR-yfi-JSxVkAHBH0wS61bFNn0',
    appId: '1:1082985809440:web:1ef63c441ba50bed36de45',
    messagingSenderId: '1082985809440',
    projectId: 'draftbrandstore',
    authDomain: 'draftbrandstore.firebaseapp.com',
    storageBucket: 'draftbrandstore.appspot.com',
    measurementId: 'G-XTXNNFRL6V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASIQOWOMhNee98dk4Qw8KYW5dspVCB9Hk',
    appId: '1:1082985809440:android:dcc3b730331605ca36de45',
    messagingSenderId: '1082985809440',
    projectId: 'draftbrandstore',
    storageBucket: 'draftbrandstore.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ0RSzLB3MKWsBYZfRnnLyepES4l-R27I',
    appId: '1:1082985809440:ios:bdc55f663b91211836de45',
    messagingSenderId: '1082985809440',
    projectId: 'draftbrandstore',
    storageBucket: 'draftbrandstore.appspot.com',
    iosBundleId: 'com.example.draftbrandstore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZ0RSzLB3MKWsBYZfRnnLyepES4l-R27I',
    appId: '1:1082985809440:ios:eed2d29f4f3d442c36de45',
    messagingSenderId: '1082985809440',
    projectId: 'draftbrandstore',
    storageBucket: 'draftbrandstore.appspot.com',
    iosBundleId: 'com.example.draftbrandstore.RunnerTests',
  );
}
