// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_vvULTXTs3Qs6--tZ0-wEewL34G0fU54',
    appId: '1:60502507103:web:6815d04cb7ea8721f025ea',
    messagingSenderId: '60502507103',
    projectId: 'myuni-1b35c',
    authDomain: 'myuni-1b35c.firebaseapp.com',
    storageBucket: 'myuni-1b35c.appspot.com',
    measurementId: 'G-BCTWX9SGF2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRoLjrf9H_2nWU90wvDHA5cWOilPm-wOc',
    appId: '1:60502507103:android:95f603cc466a336ff025ea',
    messagingSenderId: '60502507103',
    projectId: 'myuni-1b35c',
    storageBucket: 'myuni-1b35c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQhKI8iI8eM_ygFSz-EXW5DTSyLED3xjc',
    appId: '1:60502507103:ios:04aadb00b8402ba5f025ea',
    messagingSenderId: '60502507103',
    projectId: 'myuni-1b35c',
    storageBucket: 'myuni-1b35c.appspot.com',
    iosBundleId: 'com.example.instagramCloneFlutter',
  );
}
