// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjZ9V4cUO-2tbiBnFaXp86v1d6AFFy83w',
    appId: '1:598384793676:web:38ce90ce276d4f35e73ce9',
    messagingSenderId: '598384793676',
    projectId: 'myuni-92073',
    authDomain: 'myuni-92073.firebaseapp.com',
    storageBucket: 'myuni-92073.appspot.com',
    measurementId: 'G-4VZW7N78L4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6gZEXQ6H8L79ohorpj7SlghUg2hri9co',
    appId: '1:598384793676:android:ba872cc245917f1fe73ce9',
    messagingSenderId: '598384793676',
    projectId: 'myuni-92073',
    storageBucket: 'myuni-92073.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLGq3rZN2DQWJljZyHNuEYKd4c244VxjM',
    appId: '1:598384793676:ios:1d03da18c911f1e8e73ce9',
    messagingSenderId: '598384793676',
    projectId: 'myuni-92073',
    storageBucket: 'myuni-92073.appspot.com',
    iosBundleId: 'com.example.appdev51',
  );
}
